#!/bin/bash

if  [ $# -ne 2 ] || [ $2 -lt 1 ] || [ $2 -gt 26 ] ; then
    echo $# $2
    echo 'Usage: $0 contest numberOfProblems'
    exit 0
fi

d="${0%/*}"
mkdir -p $d/contests
mkdir -p $d/contests/$1

cnt=$2
for i in {a..z} ; do
    cp $d/template.cpp $d/contests/$1/$i.cpp
    echo "add_executable($i $i.cpp)" >> $d/contests/$1/CMakeLists.txt
    (( --cnt )) || break
done
echo 'set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")' >> $d/contests/$1/CMakeLists.txt

read -p "Open in Clion? [y/n] " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]] ; then
    clion $d/contests/$1
fi
