#!/bin/bash

if  [ $# -ne 2 ] || [ $2 -lt 1 ] || [ $2 -gt 26 ] ; then
    echo $# $2
    echo 'Usage: $0 contest numberOfProblems'
    exit 0
fi

mkdir -p source
mkdir -p source/$1
cnt=$2
for i in {a..z} ; do
    cp template.cpp source/$1/$i.cpp
    echo "add_executable($i $i.cpp)" >> source/$1/CMakeLists.txt
    (( --cnt )) || break
done
echo 'set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")' >> source/$1/CMakeLists.txt

read -p "Open in Clion? [y/n] " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    clion source/$1
fi
